// <auto-generated />
using System;
using Backend_1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend_1.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260521113433_addInvoicess")]
    partial class addInvoicess
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend_1.Models.AddressModel.AddressSupplier", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("DetailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WardId")
                        .HasColumnType("int");

                    b.HasKey("AddressId");

                    b.HasIndex("SupplierId")
                        .IsUnique();

                    b.ToTable("AddressSupplier");
                });

            modelBuilder.Entity("Backend_1.Models.AddressModel.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinceId"));

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinceId");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            ProvinceId = 1,
                            ProvinceName = "Hà Nội"
                        },
                        new
                        {
                            ProvinceId = 2,
                            ProvinceName = "Thái Nguyên"
                        });
                });

            modelBuilder.Entity("Backend_1.Models.AddressModel.Ward", b =>
                {
                    b.Property<int>("WardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WardId"));

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("WardName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WardId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Ward");

                    b.HasData(
                        new
                        {
                            WardId = 1,
                            ProvinceId = 1,
                            WardName = "Dịch Vọng"
                        },
                        new
                        {
                            WardId = 2,
                            ProvinceId = 1,
                            WardName = "Dịch Vọng Hậu"
                        },
                        new
                        {
                            WardId = 3,
                            ProvinceId = 1,
                            WardName = "Mai Dịch"
                        },
                        new
                        {
                            WardId = 4,
                            ProvinceId = 1,
                            WardName = "Nghĩa Đô"
                        },
                        new
                        {
                            WardId = 5,
                            ProvinceId = 1,
                            WardName = "Quan Hoa"
                        },
                        new
                        {
                            WardId = 6,
                            ProvinceId = 1,
                            WardName = "Trung Hòa"
                        },
                        new
                        {
                            WardId = 7,
                            ProvinceId = 1,
                            WardName = "Điện Biên"
                        },
                        new
                        {
                            WardId = 8,
                            ProvinceId = 1,
                            WardName = "Kim Mã"
                        },
                        new
                        {
                            WardId = 9,
                            ProvinceId = 1,
                            WardName = "Ngọc Hà"
                        },
                        new
                        {
                            WardId = 10,
                            ProvinceId = 1,
                            WardName = "Đội Cấn"
                        },
                        new
                        {
                            WardId = 11,
                            ProvinceId = 1,
                            WardName = "Liễu Giai"
                        },
                        new
                        {
                            WardId = 12,
                            ProvinceId = 1,
                            WardName = "Láng Thượng"
                        },
                        new
                        {
                            WardId = 13,
                            ProvinceId = 1,
                            WardName = "Ô Chợ Dừa"
                        },
                        new
                        {
                            WardId = 14,
                            ProvinceId = 1,
                            WardName = "Khâm Thiên"
                        },
                        new
                        {
                            WardId = 15,
                            ProvinceId = 1,
                            WardName = "Trung Liệt"
                        },
                        new
                        {
                            WardId = 16,
                            ProvinceId = 1,
                            WardName = "Văn Miếu"
                        },
                        new
                        {
                            WardId = 17,
                            ProvinceId = 1,
                            WardName = "Đại Kim"
                        },
                        new
                        {
                            WardId = 18,
                            ProvinceId = 1,
                            WardName = "Định Công"
                        },
                        new
                        {
                            WardId = 19,
                            ProvinceId = 1,
                            WardName = "Giáp Bát"
                        },
                        new
                        {
                            WardId = 20,
                            ProvinceId = 1,
                            WardName = "Hoàng Liệt"
                        },
                        new
                        {
                            WardId = 21,
                            ProvinceId = 1,
                            WardName = "Khương Đình"
                        },
                        new
                        {
                            WardId = 22,
                            ProvinceId = 1,
                            WardName = "Khương Mai"
                        },
                        new
                        {
                            WardId = 23,
                            ProvinceId = 1,
                            WardName = "Nhân Chính"
                        },
                        new
                        {
                            WardId = 24,
                            ProvinceId = 1,
                            WardName = "Thanh Xuân Bắc"
                        },
                        new
                        {
                            WardId = 25,
                            ProvinceId = 2,
                            WardName = "Tân Thịnh"
                        },
                        new
                        {
                            WardId = 26,
                            ProvinceId = 2,
                            WardName = "Trung Thành"
                        },
                        new
                        {
                            WardId = 27,
                            ProvinceId = 2,
                            WardName = "Hoàng Văn Thụ"
                        },
                        new
                        {
                            WardId = 28,
                            ProvinceId = 2,
                            WardName = "Phan Đình Phùng"
                        },
                        new
                        {
                            WardId = 29,
                            ProvinceId = 2,
                            WardName = "Quang Trung"
                        },
                        new
                        {
                            WardId = 30,
                            ProvinceId = 2,
                            WardName = "Túc Duyên"
                        },
                        new
                        {
                            WardId = 31,
                            ProvinceId = 2,
                            WardName = "Gia Sàng"
                        },
                        new
                        {
                            WardId = 32,
                            ProvinceId = 2,
                            WardName = "Cam Giá"
                        },
                        new
                        {
                            WardId = 33,
                            ProvinceId = 2,
                            WardName = "Đồng Quang"
                        },
                        new
                        {
                            WardId = 34,
                            ProvinceId = 2,
                            WardName = "Ba Hàng"
                        },
                        new
                        {
                            WardId = 35,
                            ProvinceId = 2,
                            WardName = "Bãi Bông"
                        },
                        new
                        {
                            WardId = 36,
                            ProvinceId = 2,
                            WardName = "Đồng Tiến"
                        },
                        new
                        {
                            WardId = 37,
                            ProvinceId = 2,
                            WardName = "Nam Tiến"
                        },
                        new
                        {
                            WardId = 38,
                            ProvinceId = 2,
                            WardName = "Cải Đan"
                        },
                        new
                        {
                            WardId = 39,
                            ProvinceId = 2,
                            WardName = "Bách Quang"
                        },
                        new
                        {
                            WardId = 40,
                            ProvinceId = 2,
                            WardName = "Mỏ Chè"
                        },
                        new
                        {
                            WardId = 41,
                            ProvinceId = 2,
                            WardName = "Hùng Sơn"
                        },
                        new
                        {
                            WardId = 42,
                            ProvinceId = 2,
                            WardName = "La Bằng"
                        },
                        new
                        {
                            WardId = 43,
                            ProvinceId = 2,
                            WardName = "Chùa Hang"
                        },
                        new
                        {
                            WardId = 44,
                            ProvinceId = 2,
                            WardName = "Hóa Thượng"
                        },
                        new
                        {
                            WardId = 45,
                            ProvinceId = 2,
                            WardName = "Đình Cả"
                        },
                        new
                        {
                            WardId = 46,
                            ProvinceId = 2,
                            WardName = "Chợ Chu"
                        },
                        new
                        {
                            WardId = 47,
                            ProvinceId = 2,
                            WardName = "Đu"
                        });
                });

            modelBuilder.Entity("Backend_1.Models.Carts.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CartId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Backend_1.Models.Carts.CartItems", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Backend_1.Models.Client.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Debt")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Backend_1.Models.Invoice.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExportDateProduct")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InvoiceId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Backend_1.Models.Invoice.InvoiceDetail", b =>
                {
                    b.Property<int>("InvoiceDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceDetailId"));

                    b.Property<int>("ExportProduct")
                        .HasColumnType("int");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.HasKey("InvoiceDetailId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("productId");

                    b.ToTable("InvoiceDetail");
                });

            modelBuilder.Entity("Backend_1.Models.Oders.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Backend_1.Models.Oders.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("Backend_1.Models.Products.Category", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoryId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("categoryname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("categoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            categoryId = 1,
                            IsActive = true,
                            categoryname = "Kem"
                        },
                        new
                        {
                            categoryId = 2,
                            IsActive = true,
                            categoryname = "Sữa Chua"
                        });
                });

            modelBuilder.Entity("Backend_1.Models.Products.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Expery")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("ImportPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("UnitId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Backend_1.Models.Products.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneSupplier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierId");

                    b.ToTable("Supplierss");
                });

            modelBuilder.Entity("Backend_1.Models.Products.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitId"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UnitId");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            UnitId = 1,
                            Description = "Đơn vị tính theo hộp",
                            IsActive = true,
                            UnitName = "Hộp"
                        },
                        new
                        {
                            UnitId = 2,
                            Description = "Đơn vị tính theo que/cây",
                            IsActive = true,
                            UnitName = "Que"
                        },
                        new
                        {
                            UnitId = 3,
                            Description = "Đơn vị tính theo thùng đại lý",
                            IsActive = true,
                            UnitName = "Thùng"
                        });
                });

            modelBuilder.Entity("Backend_1.Models.Users.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<bool>("IsDefaut")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receiverphone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Backend_1.Models.Users.Profiles", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Backend_1.Models.Users.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsProfile")
                        .HasColumnType("bit");

                    b.Property<string>("NumberPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            FullName = "Quản Trị Viên Hệ Thống",
                            IsProfile = false,
                            NumberPhone = "+84973987654",
                            PassWord = "AQAAAAIAAYagAAAAEH4XzC2dpdKS8EqRpcSzbAqVKCegvmHTiG8DjO5XQyn8WXnqhNVJXC2wN186fzEZTw==",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("Backend_1.Models.AddressModel.AddressSupplier", b =>
                {
                    b.HasOne("Backend_1.Models.Products.Supplier", "Suppliers")
                        .WithOne("Addresss")
                        .HasForeignKey("Backend_1.Models.AddressModel.AddressSupplier", "SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("Backend_1.Models.AddressModel.Ward", b =>
                {
                    b.HasOne("Backend_1.Models.AddressModel.Province", "Province")
                        .WithMany("wasrds")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Backend_1.Models.Carts.Cart", b =>
                {
                    b.HasOne("Backend_1.Models.Users.User", "User")
                        .WithOne("carts")
                        .HasForeignKey("Backend_1.Models.Carts.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend_1.Models.Carts.CartItems", b =>
                {
                    b.HasOne("Backend_1.Models.Carts.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_1.Models.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend_1.Models.Invoice.InvoiceDetail", b =>
                {
                    b.HasOne("Backend_1.Models.Invoice.Invoice", "Invoice")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_1.Models.Products.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("product");
                });

            modelBuilder.Entity("Backend_1.Models.Oders.Order", b =>
                {
                    b.HasOne("Backend_1.Models.Users.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend_1.Models.Oders.OrderItem", b =>
                {
                    b.HasOne("Backend_1.Models.Oders.Order", "order")
                        .WithMany("orderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_1.Models.Products.Product", "product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("order");

                    b.Navigation("product");
                });

            modelBuilder.Entity("Backend_1.Models.Products.Product", b =>
                {
                    b.HasOne("Backend_1.Models.Products.Category", "Category")
                        .WithMany("products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_1.Models.Products.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_1.Models.Products.Unit", "Unit")
                        .WithMany("Products")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Backend_1.Models.Users.Address", b =>
                {
                    b.HasOne("Backend_1.Models.Users.User", "user")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Backend_1.Models.Users.Profiles", b =>
                {
                    b.HasOne("Backend_1.Models.Users.User", "user")
                        .WithOne("Profile")
                        .HasForeignKey("Backend_1.Models.Users.Profiles", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Backend_1.Models.AddressModel.Province", b =>
                {
                    b.Navigation("wasrds");
                });

            modelBuilder.Entity("Backend_1.Models.Carts.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Backend_1.Models.Invoice.Invoice", b =>
                {
                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("Backend_1.Models.Oders.Order", b =>
                {
                    b.Navigation("orderItems");
                });

            modelBuilder.Entity("Backend_1.Models.Products.Category", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("Backend_1.Models.Products.Supplier", b =>
                {
                    b.Navigation("Addresss")
                        .IsRequired();

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Backend_1.Models.Products.Unit", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Backend_1.Models.Users.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Orders");

                    b.Navigation("Profile");

                    b.Navigation("carts");
                });
#pragma warning restore 612, 618
        }
    }
}
