// <auto-generated />
using System;
using Backend_1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend_1.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260519071202_abc")]
    partial class abc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend_1.Models.AddressModel.AddressSupplier", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("DetailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WardId")
                        .HasColumnType("int");

                    b.HasKey("AddressId");

                    b.HasIndex("SupplierId")
                        .IsUnique();

                    b.ToTable("AddressSupplier");
                });

            modelBuilder.Entity("Backend_1.Models.AddressModel.District", b =>
                {
                    b.Property<int>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistrictId"));

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("DistrictId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("District");

                    b.HasData(
                        new
                        {
                            DistrictId = 1,
                            DistrictName = "Cầu Giấy",
                            ProvinceId = 1
                        },
                        new
                        {
                            DistrictId = 2,
                            DistrictName = "Ba Đình",
                            ProvinceId = 1
                        },
                        new
                        {
                            DistrictId = 3,
                            DistrictName = "Đống Đa",
                            ProvinceId = 1
                        },
                        new
                        {
                            DistrictId = 4,
                            DistrictName = "Thành phố Thái Nguyên",
                            ProvinceId = 2
                        },
                        new
                        {
                            DistrictId = 5,
                            DistrictName = "Phổ Yên",
                            ProvinceId = 2
                        },
                        new
                        {
                            DistrictId = 6,
                            DistrictName = "Sông Công",
                            ProvinceId = 2
                        });
                });

            modelBuilder.Entity("Backend_1.Models.AddressModel.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinceId"));

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinceId");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            ProvinceId = 1,
                            ProvinceName = "Hà Nội"
                        },
                        new
                        {
                            ProvinceId = 2,
                            ProvinceName = "Thái Nguyên"
                        });
                });

            modelBuilder.Entity("Backend_1.Models.AddressModel.Ward", b =>
                {
                    b.Property<int>("WardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WardId"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("WardName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WardId");

                    b.HasIndex("DistrictId");

                    b.ToTable("Ward");

                    b.HasData(
                        new
                        {
                            WardId = 1,
                            DistrictId = 1,
                            WardName = "Dịch Vọng"
                        },
                        new
                        {
                            WardId = 2,
                            DistrictId = 1,
                            WardName = "Dịch Vọng Hậu"
                        },
                        new
                        {
                            WardId = 3,
                            DistrictId = 2,
                            WardName = "Điện Biên"
                        },
                        new
                        {
                            WardId = 4,
                            DistrictId = 2,
                            WardName = "Kim Mã"
                        },
                        new
                        {
                            WardId = 5,
                            DistrictId = 3,
                            WardName = "Láng Thượng"
                        },
                        new
                        {
                            WardId = 6,
                            DistrictId = 3,
                            WardName = "Ô Chợ Dừa"
                        },
                        new
                        {
                            WardId = 7,
                            DistrictId = 4,
                            WardName = "Tân Thịnh"
                        },
                        new
                        {
                            WardId = 8,
                            DistrictId = 4,
                            WardName = "Trung Thành"
                        },
                        new
                        {
                            WardId = 9,
                            DistrictId = 5,
                            WardName = "Bãi Bông"
                        },
                        new
                        {
                            WardId = 10,
                            DistrictId = 5,
                            WardName = "Đồng Tiến"
                        },
                        new
                        {
                            WardId = 11,
                            DistrictId = 6,
                            WardName = "Cải Đan"
                        },
                        new
                        {
                            WardId = 12,
                            DistrictId = 6,
                            WardName = "Bách Quang"
                        });
                });

            modelBuilder.Entity("Backend_1.Models.Carts.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CartId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Backend_1.Models.Carts.CartItems", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Backend_1.Models.Oders.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Backend_1.Models.Oders.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("Backend_1.Models.Products.Category", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoryId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("categoryname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("categoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            categoryId = 1,
                            IsActive = true,
                            categoryname = "Kem"
                        },
                        new
                        {
                            categoryId = 2,
                            IsActive = true,
                            categoryname = "Sữa Chua"
                        });
                });

            modelBuilder.Entity("Backend_1.Models.Products.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Expery")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("ImportPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("UnitId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Backend_1.Models.Products.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneSupplier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierId");

                    b.ToTable("Supplierss");
                });

            modelBuilder.Entity("Backend_1.Models.Products.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitId"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UnitId");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            UnitId = 1,
                            Description = "Đơn vị tính theo hộp",
                            IsActive = true,
                            UnitName = "Hộp"
                        },
                        new
                        {
                            UnitId = 2,
                            Description = "Đơn vị tính theo que/cây",
                            IsActive = true,
                            UnitName = "Que"
                        },
                        new
                        {
                            UnitId = 3,
                            Description = "Đơn vị tính theo thùng đại lý",
                            IsActive = true,
                            UnitName = "Thùng"
                        });
                });

            modelBuilder.Entity("Backend_1.Models.Users.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("Distrist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefaut")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receiverphone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Backend_1.Models.Users.Profiles", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Backend_1.Models.Users.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsProfile")
                        .HasColumnType("bit");

                    b.Property<string>("NumberPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            FullName = "Quản Trị Viên Hệ Thống",
                            IsProfile = false,
                            NumberPhone = "+84973987654",
                            PassWord = "AQAAAAIAAYagAAAAEH4XzC2dpdKS8EqRpcSzbAqVKCegvmHTiG8DjO5XQyn8WXnqhNVJXC2wN186fzEZTw==",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("Backend_1.Models.AddressModel.AddressSupplier", b =>
                {
                    b.HasOne("Backend_1.Models.Products.Supplier", "Suppliers")
                        .WithOne("Addresss")
                        .HasForeignKey("Backend_1.Models.AddressModel.AddressSupplier", "SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("Backend_1.Models.AddressModel.District", b =>
                {
                    b.HasOne("Backend_1.Models.AddressModel.Province", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Backend_1.Models.AddressModel.Ward", b =>
                {
                    b.HasOne("Backend_1.Models.AddressModel.District", "District")
                        .WithMany("Wards")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("Backend_1.Models.Carts.Cart", b =>
                {
                    b.HasOne("Backend_1.Models.Users.User", "User")
                        .WithOne("carts")
                        .HasForeignKey("Backend_1.Models.Carts.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend_1.Models.Carts.CartItems", b =>
                {
                    b.HasOne("Backend_1.Models.Carts.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_1.Models.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend_1.Models.Oders.Order", b =>
                {
                    b.HasOne("Backend_1.Models.Users.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend_1.Models.Oders.OrderItem", b =>
                {
                    b.HasOne("Backend_1.Models.Oders.Order", "order")
                        .WithMany("orderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_1.Models.Products.Product", "product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("order");

                    b.Navigation("product");
                });

            modelBuilder.Entity("Backend_1.Models.Products.Product", b =>
                {
                    b.HasOne("Backend_1.Models.Products.Category", "Category")
                        .WithMany("products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_1.Models.Products.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_1.Models.Products.Unit", "Unit")
                        .WithMany("Products")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Backend_1.Models.Users.Address", b =>
                {
                    b.HasOne("Backend_1.Models.Users.User", "user")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Backend_1.Models.Users.Profiles", b =>
                {
                    b.HasOne("Backend_1.Models.Users.User", "user")
                        .WithOne("Profile")
                        .HasForeignKey("Backend_1.Models.Users.Profiles", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Backend_1.Models.AddressModel.District", b =>
                {
                    b.Navigation("Wards");
                });

            modelBuilder.Entity("Backend_1.Models.AddressModel.Province", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("Backend_1.Models.Carts.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Backend_1.Models.Oders.Order", b =>
                {
                    b.Navigation("orderItems");
                });

            modelBuilder.Entity("Backend_1.Models.Products.Category", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("Backend_1.Models.Products.Supplier", b =>
                {
                    b.Navigation("Addresss")
                        .IsRequired();

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Backend_1.Models.Products.Unit", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Backend_1.Models.Users.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Orders");

                    b.Navigation("Profile");

                    b.Navigation("carts");
                });
#pragma warning restore 612, 618
        }
    }
}
